"""add folders table and note.folder_id

Revision ID: ff98cb4c29d0
Revises: e50ab5871386
Create Date: 2026-09-14 22:44:01.215381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff98cb4c29d0'
down_revision: Union[str, None] = 'e50ab5871386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('key_id', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.item_id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.item_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.add_column('notes', sa.Column('folder_id', sa.String(), nullable=True))
    op.create_foreign_key('fk_notes_folder_id_folders', 'notes', 'folders', ['folder_id'], ['item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_notes_folder_id_folders', 'notes', type_='foreignkey')
    op.drop_column('notes', 'folder_id')
    op.drop_table('folders')
    # ### end Alembic commands ###
